FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux \
    go build -ldflags="-w -s" -o zeropad-backend .

FROM gcr.io/distroless/static-debian12
COPY --from=builder /app/zeropad-backend /zeropad-backend
EXPOSE 8080
ENTRYPOINT ["/zeropad-backend"]
