[k3s_server]
zeropad-server ansible_host=129.213.95.227 ansible_user=opc ansible_ssh_private_key_file=~/.ssh/zeropad_deploy_rsa

[k3s_agent]
zeropad-worker ansible_host=WORKER_PUBLIC_IP_PLACEHOLDER ansible_user=opc ansible_ssh_private_key_file=~/.ssh/zeropad_deploy_rsa

[k3s_cluster:children]
k3s_server
k3s_agent
