apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: zeropad-pg-daily
  namespace: postgres
spec:
  schedule: "0 2 * * *"
  backupOwnerReference: self
  cluster:
    name: zeropad-pg
